---
title: "`r params$title`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
params:
    results: tibble_from_results_all
    title: DESeq results
    top: 3000
---

```{r setup, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(dplyr)
# dev versions on github
library(d3scatter)
library(DT)
library(hciR)

res <-  params$results

x <-  res[order(res$padj), ]
## slow if too many genes
x <- head(x, params$top)
x <- dplyr::select(x,  id, gene_name, biotype, description, baseMean, log2FoldChange, padj )

x$baseMean <-  round(x$baseMean,1)
x$log2FoldChange <-  round(x$log2FoldChange,3)
x$padj <- signif(x$padj, 4)


# add hyperlinks
x$id <-  paste0('<a href="http://www.ensembl.org/id/', x$id, '" target="_blank">', x$id,  '</a>')
sd <- SharedData$new( x)
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r sliders}
filter_slider("mean", "log10 Base mean", sd, ~round(log10(baseMean), 1) , step = 0.1 )
filter_slider("fc", "log2 Fold change absolute value ", sd, ~ round(abs(log2FoldChange),1), step = 0.1)
filter_slider("padj", "-log10 Adjusted p-value", sd, ~ round(-log10(padj) ), step = 0.1)
```

Row 1
-----------------------------------------------------------------------

### MA-plot

```{r ma_plot}
d3scatter(sd, x = ~ log10(baseMean), y = ~log2FoldChange, color= "blue",
    x_label = "log10 Base mean", y_label = "log2 Fold change")

```

### Volcano plot

```{r volcano}
d3scatter(sd, x = ~log2FoldChange, y = ~ -log10(padj), color= "blue",
    x_label = "log2 Fold change", y_label = "-log10 p-value")

```

Row 2
-----------------------------------------------------------------------

### Table

```{r dt}

datatable(sd, rownames = FALSE, escape=2, extensions = c('Scroller', 'Buttons'),
   options = list(
  scrollY = 200,  scroller = TRUE,
  dom = "Bfrtip",
  buttons = c('copy', 'csv', 'excel', 'pdf')))

```
